### ISSUE TITLE
Doesn't work on Windows or Linux

### ISSUE THREAD

**Issue by gabrielflorit** [danielchasehooper/CodeBook#2]
Would be great if you offered an alternative to the Command key. I had to deal with this issue recently for my own live coding app, http://gabrielflor.it/water - this might be of help: https://github.com/gabrielflorit/water/commit/3ec7abdb689925a62ff5914a053b5a5b56c829d7

**Comment by danielchasehooper** [comment]
Yeah, I'm aware of the issue. I'm actually trying to move away from a keyboard combination, since it's not very discoverable. Thanks for the heads up!

**Comment by danielchasehooper** [comment]
Added support for Alt. Fixed in bec6364dfe078b7034c81de71ae42303b3a08805

http://danielchasehooper.github.com/CodeBook/
