### ISSUE TITLE
Inspection problem with Gecko aka firefox engine 

### ISSUE THREAD

**Issue by arabcoders** [danielchasehooper/CodeBook#6]
Hi

There is a problem with inspection it doesn't highlight the code or the change the color in the inspection area, however it does work well in webkit-based browsers i tested Safari, Chrome both works nice

Thank you

**Comment by danielchasehooper** [comment]
I haven't put any effort into making this work on non-webkit browsers. I'd appreciate any contributions in that area.

**Comment by arabcoders** [comment]
i'll try to see what i can do but im not good at frontend development ^^
